backend/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.views import AuthorViewSet, get_site_stuff, CategoryViewSet, NewsViewsSet, IssueViewSet, EditorViewSet, \
    ColleagueViewSet, FlatPageViewSet, ArticleViewSet, index

router = routers.DefaultRouter(trailing_slash=False)

router.register(r'authors', AuthorViewSet)
router.register(r'colleagues', ColleagueViewSet)
router.register(r'editors', EditorViewSet)

router.register(r'articles', ArticleViewSet)

router.register(r'issues', IssueViewSet)
router.register(r'news', NewsViewsSet)
router.register(r'categories', CategoryViewSet)
router.register(r'flatpages', FlatPageViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^index', index),
    url(r'^site', get_site_stuff),
]

backend/studia_pigoniana/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import ListView, DetailView, TemplateView
import api.urls
from mainapp.models import Issue, Article, Author, Editor, Colleague, News, CustomFlatPage
from mainapp.views import IssueDetailView, CategoryDetailView
from django.conf import settings
from django.conf.urls.static import static
from mainapp.admin import admin_help
from mainapp.views import index

urlpatterns = [
    url(r'^admin/help$', admin_help, name='admin-help'),

    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api.urls, namespace="api")),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^artykul/(?P<slug>[-\w]+)$', DetailView.as_view(model=Article), name='article-detail'),
    url(r'^kategorie/(?P<slug>[-\w]+)$', CategoryDetailView.as_view(), name='category-detail'),
    url(r'^dodatkowe/(?P<link>[-\w]+)$',
        DetailView.as_view(model=CustomFlatPage,
                           slug_url_kwarg='link',
                           slug_field='link',
                           template_name='mainapp/flat_page.html'),
        name='flat-page'),

    url(r'^archiwum/$', ListView.as_view(queryset=Issue.objects.all(), ordering='-date'), name='issue-list'),
    url(r'^numer/(?P<date>\d+)$', IssueDetailView.as_view(), name='issue-detail'),

    url(r'^autor/(?P<slug>[-\w]+)$',
        DetailView.as_view(model=Author, template_name='mainapp/person_detail.html'), name='author-detail'),
    url(r'^autorzy/$',
        ListView.as_view(model=Author, template_name='mainapp/person_list.html'), name='author-list'),

    url(r'^redaktor/(?P<slug>[-\w]+)$',
        DetailView.as_view(model=Editor, template_name='mainapp/person_detail.html'), name='editor-detail'),
    url(r'^redaktorzy/$',
        ListView.as_view(model=Editor, template_name='mainapp/person_list.html'), name='editor-list'),

    url(r'^wspolpracownik/(?P<slug>[-\w]+)$',
        DetailView.as_view(model=Colleague, template_name='mainapp/person_detail.html'), name='colleague-detail'),
    url(r'^wspolpracownicy/$',
        ListView.as_view(model=Colleague, template_name='mainapp/person_list.html'), name='colleague-list'),

    url(r'^newsy/$',
        ListView.as_view(queryset=News.objects.all(), ordering='-created_at', paginate_by=12), name='news-list'),

    url(r'^news/(?P<slug>[-\w]+)$', DetailView.as_view(model=News), name='news-detail'),

    url(r'^$', index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [url(r'^404', TemplateView.as_view(template_name='404.html'))]
    urlpatterns += [url(r'^500', TemplateView.as_view(template_name='500.html'))]
    urlpatterns += [url(r'^403', TemplateView.as_view(template_name='403.html'))]

backend/mainapp/models.py
from abc import abstractmethod
import os
from django.core.validators import RegexValidator
from django.db import models
from autoslug import AutoSlugField
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.urls import reverse
from tinymce.models import HTMLField


class Person(models.Model):
    avatar = None
    name_prefix = models.CharField(max_length=20, verbose_name='Tytuł', null=True, blank=True)
    full_name = models.CharField(max_length=80, verbose_name='Imię i nazwisko')
    slug = AutoSlugField(populate_from='full_name', unique=True, always_update=True)
    order = models.DecimalField(max_digits=3, decimal_places=0,
                                verbose_name='W kolejności', default=999)
    description = HTMLField(verbose_name='Opis', blank=True, null=True)
    short_description = models.TextField(verbose_name='Krótki opis', blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return '%s %s' % (self.name_prefix or '', self.full_name)

    @property
    def avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return static('images/no-avatar.png')


class Author(Person):
    avatar = models.ImageField(upload_to='avatars/author/',
                               verbose_name='Zdjęcie',
                               blank=True, null=True)

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autorzy'

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'slug': self.slug})

    @property
    def articles(self):
        return self.article_set.filter(published=True)

    def list_url(self):
        return reverse('author-list')


class Editor(Person):
    function = models.CharField(max_length=40, verbose_name='Stanowisko',
                                blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/editor/',
                               verbose_name='Zdjęcie',
                               blank=True, null=True)

    class Meta:
        verbose_name = 'Redaktor'
        verbose_name_plural = 'Redaktorzy'

    def list_url(self):
        return reverse('editor-list')

    def get_absolute_url(self):
        return reverse('editor-detail', kwargs={'slug': self.slug})


class Colleague(Person):
    function = models.CharField(max_length=40, verbose_name='Stanowisko',
                                blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/colleague/',
                               verbose_name='Zdjęcie',
                               blank=True, null=True)

    class Meta:
        verbose_name = 'Współpracownik'
        verbose_name_plural = 'Współpracownicy'

    def list_url(self):
        return reverse('colleague-list')

    def get_absolute_url(self):
        return reverse('colleague-detail', kwargs={'slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='Nazwa')
    slug = AutoSlugField(populate_from='name')

    class Meta:
        verbose_name = 'Kategoria'
        verbose_name_plural = 'Kategorie'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('category-detail', kwargs={'slug': self.slug})

    def article_and_news_list(self):
        n = list(self.news_set.all()) + list(self.article_set.all())
        return n


class Issue(models.Model):
    title = models.CharField(max_length=100, verbose_name='Tytuł', blank=True, null=True)
    date = models.IntegerField(verbose_name='Rocznik', validators=[RegexValidator(regex='^20\d{2}$')], unique=True)
    description = HTMLField(verbose_name='Opis', blank=True, null=True)
    cover = models.ImageField(upload_to='issues/', verbose_name='Okładka', blank=True, null=True)
    current = models.BooleanField(default=False, verbose_name='To jest aktualny numer')
    short_description = models.TextField(verbose_name='Krótki opis',
                                                    blank=True, null=True,
                                                    help_text='Wyświetlany jeśli nie ma żadnych artykułów.')

    alternative_link = models.CharField(max_length=200, verbose_name='Alternatywny link', blank=True, null=True)

    class Meta:
        verbose_name = 'Numer'
        verbose_name_plural = 'Numery'
        ordering = ('-date',)

    def __str__(self):
        return '%s' % self.date

    def get_absolute_url(self):
        if self.alternative_link:
            return '%s' % self.alternative_link
        else:
            return reverse('issue-detail', kwargs={'date': self.date})

    @property
    def cover_url(self):
        if self.cover and hasattr(self.cover, 'url'):
            return self.cover.url
        else:
            return static('images/no-img.png')

    @property
    def articles(self):
        return self.article_set.filter(published=True)

    @classmethod
    def get_current_issue(cls):
        try:
            return cls.objects.get(current=True)
        except cls.DoesNotExist:
            return None
        except cls.MultipleObjectsReturned:
            result = cls.objects.filter(current=True)[0]
            cls.objects.exclude(pk=result.pk).update(current=False)
            return result

    @property
    def slug(self):
        return self.date

    @property
    def next(self):
        try:
            return Issue.objects.filter(date__gt=self.date).order_by('date')[0]
        except (IndexError, AttributeError):
            return None

    @property
    def prev(self):
        try:
            return Issue.objects.filter(date__lt=self.date).order_by('-date')[0]
        except (IndexError, AttributeError):
            return None

    def save(self, *args, **kw):
        # only one number may be current
        old = Issue.objects.get(pk=self.pk) if self.pk else None
        super(Issue, self).save(*args, **kw)
        if old and self.current:
            Issue.objects.exclude(pk=self.pk).update(current=False)


class Article(models.Model):
    belong_to = models.ForeignKey(Issue, verbose_name='Numer', blank=True, null=True, on_delete=models.PROTECT)
    title = models.CharField(max_length=120, verbose_name='Tytuł')
    slug = AutoSlugField(populate_from='title', unique=True, always_update=True)

    description = models.TextField(verbose_name='Opis', null=True, blank=True)
    body = HTMLField(verbose_name='Tekst')

    authors = models.ManyToManyField(Author, verbose_name='Autorzy', blank=True)
    categories = models.ManyToManyField(Category, verbose_name='Kategorie', blank=True)

    created_at = models.DateField(auto_now_add=True, verbose_name='Stworzony dnia')
    published = models.BooleanField(default=False, verbose_name='Opublikowany')

    class Meta:
        verbose_name = 'Artykuł'
        verbose_name_plural = 'Artykuły'

    def __str__(self):
        if self.published:
            return '%s' % self.title
        else:
            return '[!NIEOPUBLIKOWANY!]%s' % self.title

    def get_absolute_url(self):
        return reverse('article-detail', kwargs={'slug': self.slug})

    @property
    def date(self):
        return self.belong_to.date


class News(models.Model):
    title = models.CharField(max_length=120, verbose_name='Tytuł')
    slug = AutoSlugField(populate_from='title', unique=True)
    body = HTMLField(verbose_name='Tekst')
    categories = models.ManyToManyField(Category, verbose_name='Kategorie', blank=True)
    created_at = models.DateField(auto_now_add=True, verbose_name='Stworzony dnia')

    class Meta:
        ordering = ('pk',)
        verbose_name = 'News'
        verbose_name_plural = 'Newsy'

    def __str__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('news-detail', kwargs={'slug': self.slug})

    @property
    def created_at_formated(self):
        try:
            return '%s %s %s' % (self.created_at.day,
                                 ['stycznia', 'lutego', 'marca', 'kwietnia', 'maja', 'czerwca', 'lipca', 'sierpnia',
                                  'września', 'października', 'listopada', 'grudnia'][self.created_at.month-1],
                                 self.created_at.year)
        except AttributeError:
            return None

    @property
    def date(self):
        return self.created_at_formated


class CustomFlatPage(models.Model):
    link = AutoSlugField(populate_from='name', unique=True,
                         always_update=True, verbose_name='Link')
    name = models.CharField(max_length=30, verbose_name='Nazwa linku',
                            help_text='Używana w menu po lewej stronie np. Kontakt')

    title = models.CharField(max_length=70, verbose_name='Tytuł',
                             help_text='Używany na górze strony')
    body = HTMLField(verbose_name='Tekst')

    order = models.DecimalField(max_digits=2, decimal_places=0, blank=True,
                                null=True, default=99, verbose_name='Kolejność w menu')

    visible_on_sidebar = models.BooleanField(default=True, verbose_name='Pokazuj w menu')
    visible_on_footer = models.BooleanField(default=True, verbose_name='Pokazuj w stópce')

    class Meta:
        ordering = ('order', )
        verbose_name = 'Dodatkowa strona'
        verbose_name_plural = 'Dodatkowe strony'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('flat-page', kwargs={'link': self.link})

backend/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400&amp;subset=latin-ext" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <title>Studia Pigoniana - {% block title %}{% endblock %}</title>


    {% load static %}
    {% load sass_tags %}
    <link href="{% sass_src 'css/styles.sass' %}" rel="stylesheet" type="text/css"/>


</head>
<body>
            <nav id="mobile-navbar" class="navbar navbar-inverse bg-inverse fixed-top hidden-md-up">
                <button type="button" id="navbar-sidebar-open"
                        class="navbar-toggler navbar-toggler-right">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <button type="button" id="navbar-sidebar-close"
                        class="navbar-toggler navbar-toggler-right d-none">
                    <span aria-hidden="true">&times;</span>
                </button>
            </nav>


        <div id="main-wrapper" class="row"
                                             style="{% if request.GET.top == 'brisk' %}
                                                border-top: 5px solid #680223;
                                            {% else %}
                                                border-top: 5px solid #005A7B;
                                            {% endif %}">
            <div id="sidebar-wrapper" class="col-10 col-md-4 col-lg-3 sidebar-closed">
                <div id="sidebar-header">
                    <a href="{% url 'index' %}">
                        <img src="{% static 'images/logo-pig.png' %}" alt="">
                    </a>
                </div>

                <div id='sidebar-content'>
                    <ul class="list-unstyled sidebar-links">
                        <li><a href="{% url 'issue-list' %}">Archiwum</a></li>
                        {% load sidebar %}
                        {% get_current_issue as current_issue %}
                        {% if current_issue %}
                        <li><a href="{{ current_issue.get_absolute_url }}">Aktualne wydanie</a></li>
                        {% endif %}
                        {% if current_issue.next %}
                        <li><a href="{{ current_issue.next.get_absolute_url }}">Następne wydanie</a></li>
                        {% endif %}
                        <li class="separator"></li>
                        <li><a href="{% url 'editor-list' %}">Redakcja</a></li>
                        <li><a href="{% url 'colleague-list' %}">Współpracownicy</a></li>

                        <li>
                            <a href="{% url 'news-list' %}">Z pracy redakcji</a>
                        </li>

                        {% get_flat_pages_sidebar as flatpages_top %}
                        {% for flatpage in flatpages_top %}
                            <li>
                                <a href="{{ flatpage.get_absolute_url }}">{{ flatpage.name|capfirst }}</a>
                            </li>
                        {% endfor %}

                        {% block navbar_addons %}
                        {% endblock %}

                    </ul>
                </div>

                <div id="sidebar-footer">
                    <a href="http://www.pwsz.krosno.pl/" id="sidebar-footer-pwsz-logo-wrapper">
                        <img src="{% static 'images/pwsz-logo.png' %}" alt="">
                    </a>

                    <div class="separator"></div>

                    <ul id="sidebar-footer-links">
                        <li><a href="{% url 'author-list' %}">Autorzy</a></li>
                        {% get_flat_pages_footer as flatpages_footer %}

                        {% for flatpage in flatpages_footer %}
                            <li>
                                <a href="{{ flatpage.get_absolute_url }}">{{ flatpage.link_name|capfirst }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>

            <div id="content-wrapper" class="col-12 col-md-8 col-lg-9 pb-6">
                    {% block content %}
                    {% endblock %}
            </div>
        </div>



<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

backend/templates/error.html
{% extends 'base.html' %}




{% block content %}

    <div class="row">
        <div class="col-12 text-center mt-5">
            <h1 class="big-digits align-middle">
                {% block title %}{% block error_code %}{% endblock %}{% endblock %}
            </h1>

            <span class="text-muted h3">
                {% block error_description %}{% endblock %}
            </span> <br>

            <a href="{% url 'index' %}" class="text-muted smaller">
                wróć do strony
            </a>

        </div>
    </div>

{% endblock %}

backend/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Strona główna
{% endblock %}

{% block content %}
    <div class="row index-row pt-4 pb-3">
        <div class="col-11 mx-auto">
            <div class="row no-gutters">
                <div class="col-12 col-lg-6 mx-auto pr-lg-3">
                    <div class="row no-gutters">
                        <div class="col-12">
                            <a class="small-shadow float-left w-25 my-1 mr-3" href="{{ current.get_absolute_url }}">
                                <img src="{{ current.cover_url }}" class="img-fluid">
                            </a>

                            <a href="{{ current.get_absolute_url }}" class="h4">
                                <span class="text-muted">Aktualny numer - </span>{{ current.date }}
                            </a>

                            <p class="text-justify text-097rem">
                                {{ current.short_description }}
                            </p>
                        </div>
                    </div>

                    <div class="row no-gutters pr-2">
                        <a href="{{ current.get_absolute_url }}"
                           class="btn btn-primary btn-sm small-shadow ml-auto">
                            Więcej
                        </a>
                    </div>
                </div>

                {% if next %}

                <div class="col-12 hidden-lg-up separator my-4"></div>

                <div class="col-12 col-lg-6 pl-lg-3 horizontal-border-lg-left">
                    <div class="row no-gutters">
                        <div class="col-12">
                            <a class="small-shadow float-left w-25 my-1 mr-3" href="{{ next.get_absolute_url }}">
                                <img src="{{ next.cover_url }}" class="img-fluid">
                            </a>

                            <a href="{{ next.get_absolute_url }}" class="h4">
                                <span class="text-muted">Następny numer - </span>{{ next.date }}
                            </a>

                            <p class="text-justify text-097rem">
                                {{ next.short_description }}
                            </p>
                        </div>
                    </div>

                    <div class="row no-gutters pr-2">
                        <a href="{{ next.get_absolute_url }}"
                           class="btn btn-primary btn-sm small-shadow ml-auto">
                            Więcej
                        </a>
                    </div>
                </div>

                {% endif %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
                <a href="{% url 'issue-list' %}" class="index-all-link d-inline-block py-2 px-3">
                    Przeglądaj wszystkie wydania
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
                         style="height: 11px" x="0px" y="0px"
                         viewBox="0 0 451.847 451.847"
                         xml:space="preserve">
                    <g>
                        <path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744   L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284   c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"/>
                    </g>
                    </svg>
                </a>
        </div>
    </div>


    <div class="row index-row mt-4">
        <div class="col-11 mx-auto">
            <div class="row no-gutters">
                {% for news in news_list %}
                    <div class="col-12 col-lg-4 my-2 my-lg-4 index-news-list-element
                    {% if not forloop.last %}horizontal-border-lg-right{% endif %}">

                        <a href="{{ news.get_absolute_url }}" class="h5">{{ news.title }}</a>
                        <span class="text-muted d-block index-news-element-date">
                            {{ news.created_at_formated }}
                        </span>

                        <div class="mt-3 text-justify">
                            {{ news.body|safe|truncatewords_html:30 }}
                            <div class="w-100 text-right my-2">
                                <a href="{{ news.get_absolute_url }}"
                                   class="btn btn-primary btn-sm small-shadow ml-auto">
                                 Czytaj dalej
                                </a>
                            </div>
                        </div>
                    </div>

                    {% if not forloop.last %}
                        <div class="hidden-md-up separator col-12 my-4"></div>
                    {% endif %}

                {% endfor %}
                </div>
            </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
                <a href="{% url 'news-list' %}" class="index-all-link d-inline-block py-2 px-3">
                    Wszystkie newsy
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
                         style="height: 11px" x="0px" y="0px"
                         viewBox="0 0 451.847 451.847"
                         xml:space="preserve">
                    <g>
                        <path d="M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744   L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284   c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z"/>
                    </g>
                    </svg>
                </a>
        </div>
    </div>











{% endblock %}

backend/templates/paginator.html
<div class="row">
    <div class="col-12 text-center">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if show_first %}
                <li class="page-item">
                    <a href="?page=1" class="page-link">1</a>
                </li>

                <li class="page-item">
                    <button class="page-link" data-toggle="modal" data-target="#paginationModal">...</button>
                </li>

           {% endif %}

          {% for linkpage in page_numbers %}
              {% ifequal linkpage page_obj.number %}
                 <li class="page-item active"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
              {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
              {% endifequal %}
            {% endfor %}

          {% if show_last %}
                <li class="page-item">
                    <button class="page-link" data-toggle="modal" data-target="#paginationModal">...</button>
                </li>

                <li class="page-item">
                    <a href="?page=last" class="page-link">{{ pages }}</a>
                </li>
           {% endif %}
          </ul>
        </nav>
    </div>
</div>




<!-- Modal -->
<div class="modal fade" id="paginationModal" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Przejdź do strony</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col-12">
                <label class="text-muted">
                      <span class="text-muted small">Wprowadź numer od 1 do {{ pages }}</span>
                  </label>
              </div>

                      <form action="" method="get" class="w-100">
                          <div class="col-12">
                            <div class="row">
                              <input type="number" id="paginationModalInput" name="page"
                                 min="1" max="{{ pages }}" class="form-control col-4 offset-2 text-center"
                                  value="{{ page_obj.number }}">
                                <button type="submit" id="paginationModalBtn"
                                    class="btn btn-primary btn-sm col-4 ml-2">Przejdź</button>
                            </div>
                        </div>

                      </form>


          </div>

      </div>
    </div>
  </div>
</div>

<script>
    window.onload = function(e){
        $('#paginationModal').modal({show: false});
    }
</script>